### ISSUE TITLE
Build a Website

### ISSUE THREAD

**Issue by JaneMoroz** [chingu-voyages/v42-geckos-team-17#14]
**__Feature Description__**
Build a landing page or a multi-page website , which gives the user info about our app.

**__Major User Stories/tasks__**
- [x] User can use a landing page or multi-page website to get all necessary information about the app.
- [x] User can navigate through website easily 
  - [x] #18 
  - [x] #27
- [x] #15
- [x] #21
- [x] #23
- [x] #25
- [x] User can sign in/sign up to get access to his/her dashboard
  - [x] #44 
- [x] User can see prices option
  - [x] #38 
- [x] User can read reviews
  - [x] #40 
- [x] User can read info about Okane
  - [x] #32 
- [x] User can see office's locations on the map
  - [x] #34 

**__Additional Considerations__**
Include anything else that may be helpful. For example, links to external resources.
